# Generated by Django 6.0.5 on 2026-05-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_inquiry_button',
            field=models.CharField(default='Send Inquiry', max_length=100, verbose_name='Inquiry Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_section_text',
            field=models.CharField(default='Contact our expert team today for a free consultation and quote.', max_length=500, verbose_name='CTA Section Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_section_title',
            field=models.CharField(default='Ready to Start Your Project?', max_length=255, verbose_name='CTA Section Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_whatsapp_button',
            field=models.CharField(default='WhatsApp Chat', max_length=100, verbose_name='WhatsApp Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_section_title',
            field=models.CharField(default='Why Choose Us', max_length=255, verbose_name='Trust Section Title'),
        ),
    ]
