# Generated by Django 6.0.5 on 2026-05-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_certificate_options_certificate_locale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID (e.g., G-XXXXX)', max_length=255)),
                ('gtm_container_id', models.CharField(blank=True, help_text='Google Tag Manager Container ID (e.g., GTM-XXXXX)', max_length=255)),
                ('custom_head_scripts', models.TextField(blank=True, help_text='Custom scripts to be added to the <head> section')),
                ('custom_body_scripts', models.TextField(blank=True, help_text='Custom scripts to be added to the start of the <body> section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
