# Generated by Django 6.0.5 on 2026-05-14 02:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='lead_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lead Time'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='moq',
            field=models.CharField(blank=True, max_length=100, verbose_name='MOQ (Minimum Order Quantity)'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='packaging_details',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Packaging Details'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='SKU / Item No.'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Product Video URL (YouTube/Vimeo)'),
        ),
    ]
