# Generated by Django 6.0.5 on 2026-05-14 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productpage_lead_time_productpage_moq_and_more'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Local Video File'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='External Video URL (YouTube/Vimeo)'),
        ),
    ]
